server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/patientdb
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: PATIENT-SERVICE
  config:
      import: configserver:http://localhost:9296
  cloud:
    compatibility-verifier:
      enabled: false
