server:
  port: 9090
  
spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:9296
  cloud:
    gateway:
      routes:
        - id : PATIENT-SERVICE
          uri: lb://PATIENT-SERVICE
          predicates:
          - Path=/apiPatient/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: ORDER-SERVICE
#                fallbackuri: forward:/orderServiceFallback
        - id : DOCTOR-SERVICE
          uri: lb://DOCTOR-SERVICE
          predicates:
          - Path=/apiDoctor/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: PAYMENT-SERVICE
#                fallbackuri: forward:/paymentServiceFallback
        - id : APPOINTMENT-SERVICE
          uri: lb://APPOINTMENT-SERVICE
          predicates:
          - Path=/apiAppointment/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: PRODUCT-SERVICE
#                fallbackuri: forward:/productServiceFallback
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "GET,POST,PUT,DELETE"
    compatibility-verifier:
      enabled: false